// <auto-generated />
using Action.Models;
using Action.Models.Core;
using Action.Models.ServiceAccount;
using Action.Models.Watson;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Action.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180326040221_RelatedEntity")]
    partial class RelatedEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Action.Models.Core.Briefing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AgeRange");

                    b.Property<string>("Analysis")
                        .HasMaxLength(2147483647);

                    b.Property<string>("Brand");

                    b.Property<string>("City");

                    b.Property<int?>("ConnectedEntityId");

                    b.Property<long?>("ConnectedEntityId1");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("DocumentUrl");

                    b.Property<string>("Entity");

                    b.Property<string>("Factor");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Personality");

                    b.Property<string>("Report");

                    b.Property<string>("Report2");

                    b.Property<string>("State");

                    b.Property<int?>("Status");

                    b.Property<decimal>("Strength");

                    b.Property<string>("Tone");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedEntityId1");

                    b.ToTable("Briefings");
                });

            modelBuilder.Entity("Action.Models.Core.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("StateId");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Action.Models.Core.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Action.Models.Core.ImageRepo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Base64Image")
                        .HasMaxLength(2147483647);

                    b.Property<string>("ImageName");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Action.Models.Core.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("Action.Models.Core.Permition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionName");

                    b.Property<int>("ActionPermition");

                    b.HasKey("Id");

                    b.ToTable("Permitions");
                });

            modelBuilder.Entity("Action.Models.Core.RelationType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RelationTypes");
                });

            modelBuilder.Entity("Action.Models.Core.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(2);

                    b.Property<int?>("CountryId");

                    b.Property<string>("Name")
                        .HasMaxLength(180);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Action.Models.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<int?>("AccountId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<int?>("PlanId");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Surname");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.HasIndex("PlanId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Action.Models.Core.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("Action.Models.Plans.Features", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("PlanId");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Action.Models.Plans.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("Slug");

                    b.Property<int>("TypePlan");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Action.Models.Plans.SecondaryPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<int>("AllowedUsers");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SecondaryPlans");
                });

            modelBuilder.Entity("Action.Models.Scrap.BrickedSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Step")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .HasMaxLength(400);

                    b.Property<string>("Url")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("BrickedSources");
                });

            modelBuilder.Entity("Action.Models.Scrap.EntityMentions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<long>("EntityId");

                    b.Property<int>("ScrapSourceId");

                    b.Property<Guid>("ScrapedPageId");

                    b.HasKey("Id");

                    b.ToTable("EntityMentions");
                });

            modelBuilder.Entity("Action.Models.Scrap.ScrapedPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Hash");

                    b.Property<int>("Status");

                    b.Property<string>("Text");

                    b.Property<string>("Translated");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("ScrapedPages");
                });

            modelBuilder.Entity("Action.Models.Scrap.ScrapQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<DateTime?>("EndDateTime");

                    b.Property<DateTime>("EnqueueDateTime");

                    b.Property<DateTime?>("StartDateTime");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("ScrapQueue");
                });

            modelBuilder.Entity("Action.Models.Scrap.ScrapSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<int>("Dept");

                    b.Property<string>("EndTag");

                    b.Property<int>("Limit");

                    b.Property<int>("PageStatus");

                    b.Property<string>("StarTag");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("ScrapSources");
                });

            modelBuilder.Entity("Action.Models.ServiceAccount.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActivationDate");

                    b.Property<string>("AdministratorId");

                    b.Property<string>("CompanyName");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<int?>("PlanId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("PlanId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Action.Models.Watson.Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<string>("Alias");

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("FacebookUser");

                    b.Property<string>("InstagranUser");

                    b.Property<string>("Name");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("SiteUrl");

                    b.Property<int>("Tier");

                    b.Property<string>("TweeterUser");

                    b.Property<string>("YoutubeUser");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Argument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("RelationId");

                    b.Property<string>("text");

                    b.HasKey("Id");

                    b.HasIndex("RelationId");

                    b.ToTable("Argument");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MetadataId");

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Label");

                    b.Property<Guid?>("NLUResultId");

                    b.Property<float?>("Score");

                    b.HasKey("Id");

                    b.HasIndex("NLUResultId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dbpedia_resource");

                    b.Property<Guid?>("NLUResultId");

                    b.Property<float?>("Relevance");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("NLUResultId");

                    b.ToTable("Concept");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Disambiguation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dbpedia_resource");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Disambiguation");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.DisambiguationSubtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DisambiguationId");

                    b.Property<string>("SubType");

                    b.HasKey("Id");

                    b.HasIndex("DisambiguationId");

                    b.ToTable("DisambiguationSubtype");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Emotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EmotionDocumentId");

                    b.HasKey("Id");

                    b.HasIndex("EmotionDocumentId");

                    b.ToTable("Emotion");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.EmotionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float?>("Anger");

                    b.Property<float?>("Disgust");

                    b.Property<float?>("Fear");

                    b.Property<float?>("Joy");

                    b.Property<float?>("Sadness");

                    b.HasKey("Id");

                    b.ToTable("EmotionDetail");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.EmotionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EmotionDetailId");

                    b.HasKey("Id");

                    b.HasIndex("EmotionDetailId");

                    b.ToTable("EmotionDocument");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.EmotionsKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float?>("anger");

                    b.Property<float?>("disgust");

                    b.Property<float?>("fear");

                    b.Property<float?>("joy");

                    b.Property<float?>("sadness");

                    b.HasKey("Id");

                    b.ToTable("EmotionsKeyword");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.EmotionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EmotionDetailId");

                    b.Property<Guid?>("EmotionId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("EmotionDetailId");

                    b.HasIndex("EmotionId");

                    b.ToTable("EmotionTarget");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("Count");

                    b.Property<Guid?>("DisambiguationId");

                    b.Property<long?>("EntityId");

                    b.Property<Guid?>("NLUResultId");

                    b.Property<float?>("Relevance");

                    b.Property<string>("Text");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("DisambiguationId");

                    b.HasIndex("EntityId");

                    b.HasIndex("NLUResultId");

                    b.ToTable("Entity");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.EntityRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ArgumentId");

                    b.Property<string>("text");

                    b.Property<string>("type");

                    b.HasKey("Id");

                    b.HasIndex("ArgumentId");

                    b.ToTable("EntityRelation");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MetadataId");

                    b.Property<string>("link");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Feed");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Keywords", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("NLUResultId");

                    b.Property<Guid?>("emotionsId");

                    b.Property<string>("language");

                    b.Property<float?>("relevance");

                    b.Property<string>("retrieved_url");

                    b.Property<Guid?>("sentimentId");

                    b.Property<string>("text");

                    b.HasKey("Id");

                    b.HasIndex("NLUResultId");

                    b.HasIndex("emotionsId");

                    b.HasIndex("sentimentId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Metadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("image");

                    b.Property<string>("language");

                    b.Property<DateTime>("publication_date");

                    b.Property<string>("retrieved_url");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.NLUResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EmotionId");

                    b.Property<Guid?>("MetadataId");

                    b.Property<Guid>("ScrapedPageId");

                    b.Property<Guid?>("SentimentId");

                    b.HasKey("Id");

                    b.HasIndex("EmotionId");

                    b.HasIndex("MetadataId");

                    b.HasIndex("SentimentId");

                    b.ToTable("NluResults");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Relation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("NLUResultId");

                    b.Property<string>("language");

                    b.Property<float?>("score");

                    b.Property<string>("sentence");

                    b.Property<string>("type");

                    b.HasKey("Id");

                    b.HasIndex("NLUResultId");

                    b.ToTable("Relation");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SemanticAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Normalized");

                    b.Property<string>("Text");

                    b.Property<Guid?>("VerbId");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("SemanticAction");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SemanticObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("SemanticObject");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SemanticRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ActionId");

                    b.Property<Guid?>("NLUResultId");

                    b.Property<Guid?>("ObjectId");

                    b.Property<string>("Sentence");

                    b.Property<Guid?>("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("NLUResultId");

                    b.HasIndex("ObjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SemanticRole");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SemanticSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("SemanticSubject");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SemanticVerb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Tense");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("SemanticVerb");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Sentiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RetrievedUrl");

                    b.Property<Guid?>("SentimentDocId");

                    b.HasKey("Id");

                    b.HasIndex("SentimentDocId");

                    b.ToTable("Sentiment");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SentimentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Label");

                    b.Property<float?>("Score");

                    b.HasKey("Id");

                    b.ToTable("SentimentDocument");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SentimentKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float?>("score");

                    b.HasKey("Id");

                    b.ToTable("SentimentKeyword");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SentimentTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Label");

                    b.Property<float?>("Score");

                    b.Property<Guid?>("SentimentId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("SentimentId");

                    b.ToTable("SentimentTarget");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.ConsumptionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ConsumptionPreferencesId");

                    b.Property<string>("Name");

                    b.Property<int>("Score");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionPreferencesId");

                    b.ToTable("ConsumptionDetail");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.ConsumptionPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConsumptionPreferenceId");

                    b.Property<string>("Name");

                    b.Property<Guid?>("PersonalityResultId");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityResultId");

                    b.ToTable("ConsumptionPreferences");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.Detail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double?>("Percentile");

                    b.Property<Guid?>("PersonalityId");

                    b.Property<Guid?>("PersonalityResultId");

                    b.Property<Guid?>("PersonalityResultId1");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityId");

                    b.HasIndex("PersonalityResultId");

                    b.HasIndex("PersonalityResultId1");

                    b.ToTable("Detail");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.Personality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double?>("Percentile");

                    b.Property<Guid?>("PersonalityResultId");

                    b.HasKey("Id");

                    b.HasIndex("PersonalityResultId");

                    b.ToTable("Personality");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.PersonalityResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("EntityId");

                    b.Property<int>("ScrapSourceId");

                    b.Property<Guid>("ScrapedPageId");

                    b.HasKey("Id");

                    b.ToTable("Personalities");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.DocumentTone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("DocumentTone");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.SentencesTone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("InputFrom");

                    b.Property<long?>("InputTo");

                    b.Property<long?>("SentenceId");

                    b.Property<string>("Text");

                    b.Property<Guid?>("ToneResultId");

                    b.HasKey("Id");

                    b.HasIndex("ToneResultId");

                    b.ToTable("SentencesTone");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.Tone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Score");

                    b.Property<Guid?>("ToneCategoriesId");

                    b.Property<string>("ToneId");

                    b.Property<string>("ToneName");

                    b.HasKey("Id");

                    b.HasIndex("ToneCategoriesId");

                    b.ToTable("Tone");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.ToneCategories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryId");

                    b.Property<string>("CategoryName");

                    b.Property<Guid?>("DocumentToneId");

                    b.Property<Guid?>("SentencesToneId");

                    b.HasKey("Id");

                    b.HasIndex("DocumentToneId");

                    b.HasIndex("SentencesToneId");

                    b.ToTable("ToneCategories");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.ToneResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DocumentToneId");

                    b.Property<Guid>("NluEntityId");

                    b.Property<Guid>("ScrapedPageId");

                    b.HasKey("Id");

                    b.HasIndex("DocumentToneId");

                    b.ToTable("Tones");
                });

            modelBuilder.Entity("Action.Models.Watson.WatsonCredentials", b =>
                {
                    b.Property<int>("Service");

                    b.Property<string>("Model");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.Property<string>("Version");

                    b.HasKey("Service");

                    b.ToTable("WatsonCredentials");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Action.Models.Core.Briefing", b =>
                {
                    b.HasOne("Action.Models.Watson.Entity", "ConnectedEntity")
                        .WithMany("Briefings")
                        .HasForeignKey("ConnectedEntityId1");
                });

            modelBuilder.Entity("Action.Models.Core.City", b =>
                {
                    b.HasOne("Action.Models.Core.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Action.Models.Core.State", b =>
                {
                    b.HasOne("Action.Models.Core.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Action.Models.Core.User", b =>
                {
                    b.HasOne("Action.Models.ServiceAccount.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId");

                    b.HasOne("Action.Models.Plans.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");
                });

            modelBuilder.Entity("Action.Models.Plans.Features", b =>
                {
                    b.HasOne("Action.Models.Plans.Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanId");
                });

            modelBuilder.Entity("Action.Models.Plans.SecondaryPlan", b =>
                {
                    b.HasOne("Action.Models.ServiceAccount.Account", "Account")
                        .WithMany("SecondaryPlans")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("Action.Models.ServiceAccount.Account", b =>
                {
                    b.HasOne("Action.Models.Core.User", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId");

                    b.HasOne("Action.Models.Plans.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");
                });

            modelBuilder.Entity("Action.Models.Watson.Entity", b =>
                {
                    b.HasOne("Action.Models.ServiceAccount.Account")
                        .WithMany("Entities")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Argument", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.Relation")
                        .WithMany("Arguments")
                        .HasForeignKey("RelationId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Author", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.Metadata")
                        .WithMany("Authors")
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Category", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.NLUResult")
                        .WithMany("Category")
                        .HasForeignKey("NLUResultId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Concept", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.NLUResult")
                        .WithMany("Concept")
                        .HasForeignKey("NLUResultId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.DisambiguationSubtype", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.Disambiguation", "Disambiguation")
                        .WithMany("Subtype")
                        .HasForeignKey("DisambiguationId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Emotion", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.EmotionDocument", "EmotionDocument")
                        .WithMany()
                        .HasForeignKey("EmotionDocumentId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.EmotionDocument", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.EmotionDetail", "EmotionDetail")
                        .WithMany()
                        .HasForeignKey("EmotionDetailId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.EmotionTarget", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.EmotionDetail", "EmotionDetail")
                        .WithMany()
                        .HasForeignKey("EmotionDetailId");

                    b.HasOne("Action.Models.Watson.NLU.Emotion")
                        .WithMany("EmotionTarget")
                        .HasForeignKey("EmotionId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Entity", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.Disambiguation", "Disambiguation")
                        .WithMany()
                        .HasForeignKey("DisambiguationId");

                    b.HasOne("Action.Models.Watson.Entity")
                        .WithMany("RelatedEntities")
                        .HasForeignKey("EntityId");

                    b.HasOne("Action.Models.Watson.NLU.NLUResult")
                        .WithMany("Entity")
                        .HasForeignKey("NLUResultId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.EntityRelation", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.Argument")
                        .WithMany("EntityRelations")
                        .HasForeignKey("ArgumentId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Feed", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.Metadata")
                        .WithMany("Feeds")
                        .HasForeignKey("MetadataId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Keywords", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.NLUResult")
                        .WithMany("Keywords")
                        .HasForeignKey("NLUResultId");

                    b.HasOne("Action.Models.Watson.NLU.EmotionsKeyword", "emotions")
                        .WithMany()
                        .HasForeignKey("emotionsId");

                    b.HasOne("Action.Models.Watson.NLU.SentimentKeyword", "sentiment")
                        .WithMany()
                        .HasForeignKey("sentimentId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.NLUResult", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.Emotion", "Emotion")
                        .WithMany()
                        .HasForeignKey("EmotionId");

                    b.HasOne("Action.Models.Watson.NLU.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.HasOne("Action.Models.Watson.NLU.Sentiment", "Sentiment")
                        .WithMany()
                        .HasForeignKey("SentimentId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Relation", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.NLUResult")
                        .WithMany("Relations")
                        .HasForeignKey("NLUResultId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SemanticAction", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.SemanticVerb", "Verb")
                        .WithMany()
                        .HasForeignKey("VerbId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SemanticRole", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.SemanticAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId");

                    b.HasOne("Action.Models.Watson.NLU.NLUResult")
                        .WithMany("SemanticRoles")
                        .HasForeignKey("NLUResultId");

                    b.HasOne("Action.Models.Watson.NLU.SemanticObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId");

                    b.HasOne("Action.Models.Watson.NLU.SemanticSubject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.Sentiment", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.SentimentDocument", "SentimentDoc")
                        .WithMany()
                        .HasForeignKey("SentimentDocId");
                });

            modelBuilder.Entity("Action.Models.Watson.NLU.SentimentTarget", b =>
                {
                    b.HasOne("Action.Models.Watson.NLU.Sentiment")
                        .WithMany("SentimentTarget")
                        .HasForeignKey("SentimentId");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.ConsumptionDetail", b =>
                {
                    b.HasOne("Action.Models.Watson.PersonalityInsights.ConsumptionPreferences")
                        .WithMany("ConsumptionDetails")
                        .HasForeignKey("ConsumptionPreferencesId");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.ConsumptionPreferences", b =>
                {
                    b.HasOne("Action.Models.Watson.PersonalityInsights.PersonalityResult")
                        .WithMany("ConsumptionPreferences")
                        .HasForeignKey("PersonalityResultId");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.Detail", b =>
                {
                    b.HasOne("Action.Models.Watson.PersonalityInsights.Personality")
                        .WithMany("Details")
                        .HasForeignKey("PersonalityId");

                    b.HasOne("Action.Models.Watson.PersonalityInsights.PersonalityResult")
                        .WithMany("Needs")
                        .HasForeignKey("PersonalityResultId");

                    b.HasOne("Action.Models.Watson.PersonalityInsights.PersonalityResult")
                        .WithMany("Values")
                        .HasForeignKey("PersonalityResultId1");
                });

            modelBuilder.Entity("Action.Models.Watson.PersonalityInsights.Personality", b =>
                {
                    b.HasOne("Action.Models.Watson.PersonalityInsights.PersonalityResult")
                        .WithMany("Personality")
                        .HasForeignKey("PersonalityResultId");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.SentencesTone", b =>
                {
                    b.HasOne("Action.Models.Watson.ToneAnalyze.ToneResult")
                        .WithMany("SetenceTones")
                        .HasForeignKey("ToneResultId");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.Tone", b =>
                {
                    b.HasOne("Action.Models.Watson.ToneAnalyze.ToneCategories")
                        .WithMany("Tones")
                        .HasForeignKey("ToneCategoriesId");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.ToneCategories", b =>
                {
                    b.HasOne("Action.Models.Watson.ToneAnalyze.DocumentTone")
                        .WithMany("ToneCategories")
                        .HasForeignKey("DocumentToneId");

                    b.HasOne("Action.Models.Watson.ToneAnalyze.SentencesTone")
                        .WithMany("ToneCategories")
                        .HasForeignKey("SentencesToneId");
                });

            modelBuilder.Entity("Action.Models.Watson.ToneAnalyze.ToneResult", b =>
                {
                    b.HasOne("Action.Models.Watson.ToneAnalyze.DocumentTone", "DocumentTone")
                        .WithMany()
                        .HasForeignKey("DocumentToneId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Action.Models.Core.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Action.Models.Core.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Action.Models.Core.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Action.Models.Core.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
